apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment #our deployment name
  namespace: chat-app #deployment namespace
  labels:
    app:  frontend #deployment label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend #the label which deployment will match to get it's pods
  template:
    metadata:
      labels:
        app: frontend #pod label
    spec:
      containers:
      - image:  saadnadeem07/chatapp-frontend #dockerhub image from where we will get the frontend image
        name:  chatapp-frontend #container name 
        env:
        - name:  NODE_ENV #env variable
          value:  production # env variable value
        ports:
        - containerPort:  80